stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V
  - pip install -r requirements.txt

unit_tests:
  stage: test
  script:
    - python -m unittest discover -s tests -p "test_*.py"
  artifacts:
    when: always
    paths:
      - tests/
    reports:
      junit: junit.xml
